
//get product

export const GET_PRODUCTS_REQUEST ="GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS ="GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_fAILURE ="GET_PRODUCTS_fAILURE"


//for add to cart
export const ADD_PRODUCT_CART_REQUEST = 'ADD_PRODUCT_CART_REQUEST';
export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS';
export const ADD_PRODUCT_CART_FAILURE = 'ADD_PRODUCT_CART_FAILURE';


//add to cart
export const ADD_PRODUCT_CART_REQUEST = 'ADD_PRODUCT_CART_REQUEST';
export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS';
export const ADD_PRODUCT_CART_FAILURE = 'ADD_PRODUCT_CART_FAILURE';

